---
abstract: 'Test the spelling of HTML documents'
author:
  - 'Robert Rothenberg, C<< <rrwo at cpan.org> >>'
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Slurp: 0
  Readonly: 0
  Test::Builder::Tester: 0
  Test::More: 0
  Test::Pod::Spelling: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-HTML-Spelling
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Const::Fast: 0
  Encode: 0
  HTML::Parser: 0
  List::Util: 0
  Moose: 0
  MooseX::NonMoose: 0
  Scalar::Util: 0
  Search::Tokenizer: 0
  Test::Builder: 0
  Text::Aspell: 0
  curry: 0
  perl: 5.01
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-HTML-Spelling
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/robrwo/Test-HTML-Spelling.git
version: 0.003001
